# Generated by Django 3.0.6 on 2020-05-16 07:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=256)),
                ('hash', models.CharField(default='', max_length=64)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField(default='')),
                ('fetched_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.Reference')),
            ],
        ),
    ]
