# Generated by Django 3.0.6 on 2020-05-14 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=256)),
                ('hash', models.CharField(default='', max_length=64)),
                ('title', models.CharField(default='', max_length=256)),
                ('content', models.TextField(default='')),
                ('fetched_date', models.DateTimeField()),
            ],
        ),
    ]
