# Generated by Django 3.0.6 on 2020-05-14 17:24

import csv
from collections import namedtuple
from django.conf import settings
from django.db import migrations
import functools
import itertools
import json
import logging
import os


logger = logging.getLogger(__name__)

example_directories = [
    'business-mail.jp-20200514',
    'email.chottu.net-20200514',
]

index_filename = 'INDEX.csv'

ExampleDatum = namedtuple('ExampleDatum', [
    'id',
    'filename',
    'url',
    'hash',
    'fetched_date'
])


def batched_examples_from(directory, size=10):
    index_file_path = os.path.join(directory, index_filename)

    with open(index_file_path) as f:
        index_reader = csv.reader(f)
        counter = itertools.count()

        def key(_): return next(counter) // size

        for _, g in itertools.groupby(index_reader, key):
            yield map(ExampleDatum._make, g)


def insert_examples(apps, _):
    Reference = apps.get_model('examples', 'Reference')
    Example = apps.get_model('examples', 'Example')

    def data_directory(x):
        return os.path.join(settings.BASE_DIR, 'data', x)

    def create_example(directory, reference, datum):
        def datum_asdict():
            d = datum._asdict()
            return {x: d[x] for x in datum._fields if x != 'filename'}

        with open(os.path.join(directory, datum.filename)) as f:
            details = json.load(f)

        return Example(**{
            'reference': Reference(id=reference),
            **datum_asdict(),
            **details,
        })

    size = 10

    Reference.objects.bulk_create(
        [Reference(id=d) for d in example_directories])

    for reference, directory in (
            zip(example_directories,
                map(data_directory, example_directories))):
        for data in batched_examples_from(directory, size):
            _create = functools.partial(create_example, directory, reference)
            Example.objects.bulk_create(map(_create, data), size)


def delete_examples(apps, _):
    Example = apps.get_model('examples', 'Example')
    Example.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(insert_examples, delete_examples),
    ]
