# Generated by Django 3.0.6 on 2020-05-16 08:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examples', '0002_auto_20200514_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('annotated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('example', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examples.Example')),
            ],
        ),
        migrations.AddField(
            model_name='example',
            name='annotators',
            field=models.ManyToManyField(through='examples.Annotation', to=settings.AUTH_USER_MODEL),
        ),
    ]
