# Generated by Django 3.0.6 on 2020-05-16 08:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('examples', '0003_auto_20200516_0821'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('example', 'annotated_by')},
        ),
    ]
