# Generated by Django 3.0.6 on 2020-05-16 19:04

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('examples', '0004_auto_20200516_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='content',
            field=django_mysql.models.JSONField(default=''),
        ),
    ]
