version: '3'
services:
  app:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      AUTH0_API_DOMAIN: "dev-9t4hfnwv.auth0.com"
      AUTH0_API_IDENTIFIER: "https://api.toutobu.io"
      DJANGO_LOG_LEVEL: DEBUG
  frontend:
    build: ./frontend
    command: npm run serve
    ports:
      - "3333:3333"
    volumes:
      - ./frontend:/frontend
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3309:3306"
    volumes:
      - ./db/mysql:/etc/mysql/conf.d
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: annotator_development
      MYSQL_PASSWORD: password
